apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"coredns-coredns"},"name":"coredns-coredns","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"run":"coredns-coredns"}}}
  creationTimestamp: "2020-11-25T13:45:27Z"
  labels:
    run: coredns-coredns
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:run: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:run: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2020-11-25T13:45:27Z"
  name: coredns-coredns
  namespace: default
  resourceVersion: "19847"
  selfLink: /api/v1/namespaces/default/services/coredns-coredns
  uid: cb873e66-c671-44b2-8ea2-7362fcadbff3
spec:
  clusterIP: 10.108.77.34
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: coredns-coredns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
